### ISSUE TITLE
Problem with encoding of locale string

### ISSUE THREAD

**Issue by broxtronix** [mitsuhiko/click#490] opened 2015-12-15 20:15 UTC
Hi there.  I am running a click-based python command line utility over an SSH connection using paramiko, and I see this error:
```
  File "/Users/broxton/anaconda3/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/broxton/anaconda3/lib/python3.5/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/Users/broxton/anaconda3/lib/python3.5/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    print(locale.lower().endswith(('utf-8', '.utf8')))
TypeError: a bytes-like object is required, not 'str'
```
This is on a machine running Mac OS 10.11 and Anaconda Python 3.5.

It appears that `click` is calling `locale -a` through a sub-process, and the result is being returned as a byte string rather than a Python string.  The call to `.endswith()` fails because Python refuses to compare a bytes-like object to the strings in the tuple: `('utf-8', '.utf8')`  This error does not occur when I run the command through my local shell, rather than remotely over the ssh connection.  

Coercing the locale string returned by `subprocess()` allows click to proceed further to the more informative error message:
```
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.
```
The first error seems to mask the second, so I would recommend adding a tiny bit of type coercion here from a byte to a string type here so that this code works in either case and the user can then encounter the helpful `RuntimeErrror` message that leads them to correct their locale issue.

**Comment by rsyring** [comment] 2016-01-12 13:13
I've also run into this issue when trying to run a Click application through Anicron.  Although my stack trace and error message looks a bit different:

```
Traceback (most recent call last):
  File "/usr/local/bin/kilo", line 9, in <module>
    load_entry_point('Kilo==0.1', 'console_scripts', 'kilo')()
  File "/opt/kilo/src/kilo/cli.py", line 113, in cli_entry
    cli(obj={})
  File "/opt/kilo/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/kilo/lib/python3.4/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/opt/kilo/lib/python3.4/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: 'str' does not support the buffer interface
```

I'm running Click 6.2 and Python 3.4.3.

**Comment by rsyring** [comment] 2016-01-12 19:32
Looks like this was fixed already: https://github.com/mitsuhiko/click/commit/6bc3bf977a16d948841de17a6993ee11587b75b1

**Comment by jseabold** [comment] 2016-01-18 21:00
Just ran into this too. A release that works on posix with python 3 with this fix would be much appreciated.

**Comment by keitheis** [comment] 2016-01-22 04:16
+1

**Comment by aginiewicz** [comment] 2016-01-26 17:48
Any plans on release date for version with this fix? It also happens for our continuous integration script that uses pip-tools to sync dependencies before build.

**Comment by chrisschreiner** [comment] 2016-01-28 21:07
bump

**Comment by awhillas** [comment] 2016-02-10 04:21
+1 pip-tools needs it bad :@

**Comment by carltongibson** [comment] 2016-02-10 07:41
@mitsuhiko It looks like 6.3 is ready to go; is that right? Do you need any help with bandwidth?

**Comment by untitaker** [comment] 2016-02-22 21:51
Duplicate of https://github.com/mitsuhiko/click/issues/494

**Comment by untitaker** [comment] 2016-02-22 21:57
6.3 is out, which fixes this.

The fix was in master the whole time...

**Closed by untitaker** 2016-02-22 21:57 UTC
