### ISSUE TITLE
Mutually exclusive option groups

### ISSUE THREAD

**Issue by cosminbasca** [mitsuhiko/click#509] opened 2016-02-02 16:00 UTC
Is it possible to have mutually exclusive option / argument groups ala argparse: add_mutually_exclusive_group? 

better yet, mutually exclusive groups of (mutually exclusive) groups. In essence tree like grouping strategies for option groups?

Thanks

**Comment by cosminbasca** [comment] 2016-02-04 13:00
I've implemented my own solution to support option groups and mutually exclusive option groups on top of click. If there is interest, let me know and I will try to integrate it into click and submit a pull request.

Cheers,
Cosmin

**Comment by nchammas** [comment] 2016-02-06 02:05
Dup of #257.

**Comment by pprince** [comment] 2016-02-12 22:46
@cosminbasca Could you at least link your solution here (and/or at #257, since this issue will likely be closed as a dup) as an example to others?

**Comment by untitaker** [comment] 2016-03-04 10:32
Duplicate of #257, which is already resolved (rejected) and has all information you need to implement this manually.

**Closed by untitaker** 2016-03-04 10:32 UTC
