### ISSUE TITLE
Click 6.0: UnboundLocalError: local variable 'clear_width' referenced before assignment

### ISSUE THREAD

**Issue by ivankravets** [mitsuhiko/click#465] opened 2015-11-25 09:20 UTC
Dear developers,

I received an issue from @PlatformIO's user https://github.com/platformio/platformio/issues/336
I can't reproduce it. Maybe, you have some ideas. Thanks!

The source code which causes this error: https://github.com/platformio/platformio/blob/develop/platformio/downloader.py#L71:L73

```
    with click.progressbar(length=chunks, label="Downloading") as pb:
  File "/usr/local/lib/python2.7/dist-packages/click/_termui_impl.py", line 94, in __enter__
    self.render_progress()
  File "/usr/local/lib/python2.7/dist-packages/click/_termui_impl.py", line 222, in render_progress
    buf.append(' ' * (clear_width - line_len))
UnboundLocalError: local variable 'clear_width' referenced before assignment
```

Regards, Ivan.

**Comment by mitsuhiko** [comment] 2015-11-25 09:21
Duplicate of #464.

**Closed by mitsuhiko** 2015-11-25 09:21 UTC
