### ISSUE TITLE
Error when running --help

### ISSUE THREAD

**Issue by tian2992** [mitsuhiko/click#411] opened 2015-08-21 02:38 UTC
When running the command with the --help option:

```
  File "/usr/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py", line 1222, in make_metavar
    metavar = self.type.name.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

All of the attributes have help defined.
Cheers

**Comment by untitaker** [comment] 2015-08-21 10:35
Please update your Click and provide an example that fails.

On 21 August 2015 04:38:25 CEST, Sebastian Oliva <notifications@github.com> wrote:
>When running the command with the --help option:
>
>```
>File
>"/usr/lib/python2.7/site-packages/click-4.0-py2.7.egg/click/core.py",
>line 1222, in make_metavar
>    metavar = self.type.name.upper()
>AttributeError: 'NoneType' object has no attribute 'upper'
>```
>
>All of the attributes have help defined.
>Cheers
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/411

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment] 2015-09-15 23:59
Closing this since the author didn't provide any information on how to reproduce this.

**Closed** 2015-09-15 23:58 UTC
Labels: needsinfo, testcase-needed

**Comment by dmo60** [comment] 2019-01-18 09:51
This is super old, but for all people coming here with the same problem:

In my case it was caused by using a custom `click.ParamType` which did not specify the `name` attribute. This is required to print the help text.

Example:
```
class MyType(click.ParamType):

    name = "name of your custom type"  # without this, I get the error above

    def convert(self, value, param, ctx):
        ...
```

**Comment by rotkehlxen** [comment] 2019-08-31 15:43
Thanks so much to @dmo60! I had the same problem and adding the name attribute in custom parameter type fixed it. By the way: In the documentation (section  [Implementing Custom Types](https://click.palletsprojects.com/en/7.x/parameters/) it says that the name attribute is optional - apparently it is not :-)

**Comment by jcrotts** [comment] 2019-08-31 17:01
@rotkehlxen Would you be interested in doing a documentation PR for this?

**Comment by rotkehlxen** [comment] 2019-10-27 15:01
@jcrotts What exactly wound that entail? sorry for the super late response ...
